# Generated by Django 5.2.3 on 2025-06-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('vuelo', models.CharField(max_length=50)),
                ('fecha_salida', models.DateField()),
                ('fecha_entrada', models.DateField()),
            ],
        ),
    ]
