# Generated by Django 5.2.3 on 2025-06-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabdos',
            name='fecha_creacion',
            field=models.DateField(),
        ),
    ]
