# Generated by Django 5.2.3 on 2025-06-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=11)),
                ('dia', models.DateField(auto_now_add=True)),
                ('produccion', models.IntegerField()),
            ],
        ),
    ]
