# Generated by Django 5.2.3 on 2025-06-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=100)),
                ('muestra', models.IntegerField()),
                ('aprovados', models.IntegerField()),
                ('rechazados', models.IntegerField()),
            ],
        ),
    ]
